name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run_checks:
    name: Run checks
    uses: ./.github/workflows/check.yml
  deploy_to_github_pages:
    name: Deploy to GitHub Pages
    uses: ./.github/workflows/deploy.yml
    needs:
      - run_checks
